export const DATA = [
  {
    id: '1',
    img: 'https://picsum.photos/id/1011/640/480',
    text: 'Awesome text for post 1',
    date: new Date().toJSON(),
    booked: true,
  },
  {
    id: '2',
    img: 'https://picsum.photos/id/1032/640/480',
    text: 'Awesome text for post 2',
    date: new Date().toJSON(),
    booked: true,
  },
  {
    id: '3',
    img: 'https://picsum.photos/id/1043/640/480',
    text: 'Awesome text for post 3',
    date: new Date().toJSON(),
    booked: false,
  },
  {
    id: '4',
    img: 'https://picsum.photos/id/1051/640/480',
    text: 'Awesome text for post 4',
    date: new Date().toJSON(),
    booked: true,
  },
  {
    id: '5',
    img: 'https://picsum.photos/id/1067/640/480',
    text: 'Awesome text for post 5',
    date: new Date().toJSON(),
    booked: false,
  },
  {
    id: '6',
    img: 'https://picsum.photos/id/182/640/480',
    text: 'Awesome text for post 6',
    date: new Date().toJSON(),
    booked: false,
  },
  {
    id: '7',
    img: 'https://picsum.photos/id/191/640/480',
    text: 'Awesome text for post 7',
    date: new Date().toJSON(),
    booked: true,
  },
];
